#!/usr/bin/env bash

sleep 60

CLIENTNAME=$(hostname)

if [ "$CLIENTNAME" = "Solar" ]; then
    CLIENTDESC="HP WorkStation xw4400"
    LOCALIP="`ifconfig wlan0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'`"
elif [ "$CLIENTNAME" = "Gaia" ]; then
    CLIENTDESC="HP ProBook 4330s"
    LOCALIP="`ifconfig wlan0 2>/dev/null|awk '/inet adr:/ {print $2}'|sed 's/adr://'`"
else
    CLIENTDESC="inconnu"
fi

echo " $CLIENTNAME  ($CLIENTDESC)      "