#!/bin/bash

WEBAPPNAME="Facebook"
WEBAPPURL="http://m.facebook.com"

nohup $APP_BROWSER --app=$WEBAPPURL > /dev/null 2>&1&
gmsg Gaius -ok "Ouverture de $WEBAPPNAME dans $APP_BROWSER_BIS"
sleep 1
guake -t
echo