#!/bin/bash

WEBAPPNAME="Nouveau Gmail"
WEBAPPURL="https://mail.google.com/mail/u/0/?hl=fr#inbox?compose=new"

nohup $APP_BROWSER_BIS --app=$WEBAPPURL > /dev/null 2>&1&
gmsg Gaius -ok "Ouverture de $WEBAPPNAME dans $APP_BROWSER_BIS"
sleep 1
guake -t
echo