#!/bin/bash


echo
gmsg Gaius -l -do "Execution de la commande apt-get update"
sleep 1 && sudo apt-get update
echo
gmsg Gaius -l -do "Execution de la commande apt-get upgrade"
sleep 1 && sudo apt-get upgrade
echo
gmsg Gaius -l -do "Execution de la commande apt-get dist-upgrade"
sleep 1 && sudo apt-get dist-upgrade
echo
gmsg Gaius -l -do "Execution de la commande apt-get autoclean"
sleep 1 && sudo apt-get autoclean
echo
gmsg Gaius -l -do "Execution de la commande apt-get autoremove"
sleep 1 && sudo apt-get autoremove
